// <auto-generated />
using System;
using LetsTalk.Server.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LetsTalk.Server.Persistence.Migrations
{
    [DbContext(typeof(LetsTalkDbContext))]
    [Migration("20230724014638_ImageTableAddWidthHeightColumns")]
    partial class ImageTableAddWidthHeightColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LetsTalk.Server.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalId")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("ExternalId", "AccountTypeId")
                        .IsUnique();

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("accounttypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Facebook"
                        },
                        new
                        {
                            Id = 2,
                            Name = "VK"
                        });
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeId");

                    b.ToTable("files");
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.FileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("filetypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Image"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Audio"
                        });
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int>("ImageFormatId")
                        .HasColumnType("int");

                    b.Property<int>("ImageRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("ImageFormatId");

                    b.HasIndex("ImageRoleId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.ImageFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("imageformats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jpeg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Png"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gif"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Webp"
                        },
                        new
                        {
                            Id = -1,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.ImageRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("imageroles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Avatar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Message"
                        });
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.LinkPreview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("linkpreviews");
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long?>("DateCreatedUnix")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateReadUnix")
                        .HasColumnType("bigint");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<int?>("ImagePreviewId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LinkPreviewId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<string>("TextHtml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("ImagePreviewId")
                        .IsUnique();

                    b.HasIndex("LinkPreviewId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.Account", b =>
                {
                    b.HasOne("LetsTalk.Server.Domain.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsTalk.Server.Domain.Image", "Image")
                        .WithOne("Account")
                        .HasForeignKey("LetsTalk.Server.Domain.Account", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AccountType");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.File", b =>
                {
                    b.HasOne("LetsTalk.Server.Domain.FileType", "FileType")
                        .WithMany()
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.Image", b =>
                {
                    b.HasOne("LetsTalk.Server.Domain.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsTalk.Server.Domain.ImageFormat", "ImageFormat")
                        .WithMany()
                        .HasForeignKey("ImageFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsTalk.Server.Domain.ImageRole", "ImageRole")
                        .WithMany()
                        .HasForeignKey("ImageRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("ImageFormat");

                    b.Navigation("ImageRole");
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.Message", b =>
                {
                    b.HasOne("LetsTalk.Server.Domain.Image", "Image")
                        .WithOne()
                        .HasForeignKey("LetsTalk.Server.Domain.Message", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LetsTalk.Server.Domain.Image", "ImagePreview")
                        .WithOne()
                        .HasForeignKey("LetsTalk.Server.Domain.Message", "ImagePreviewId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LetsTalk.Server.Domain.LinkPreview", "LinkPreview")
                        .WithMany()
                        .HasForeignKey("LinkPreviewId");

                    b.HasOne("LetsTalk.Server.Domain.Account", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsTalk.Server.Domain.Account", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("ImagePreview");

                    b.Navigation("LinkPreview");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LetsTalk.Server.Domain.Image", b =>
                {
                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
