<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\LetsTalk.Server.Configuration\LetsTalk.Server.Configuration.csproj" />
    <ProjectReference Include="..\LetsTalk.Server.Telemetry.Abstractions\LetsTalk.Server.Telemetry.Abstractions.csproj" />
    <ProjectReference Include="..\LetsTalk.Server.Telemetry.Models\LetsTalk.Server.Telemetry.Models.csproj" />
  </ItemGroup>

</Project>
